# A Short introduction to Julia

## Variables, Numbers, and Strings

### Variables and numerical types

Variables do not need to be declared

In [1]:
x = 3

3

but the value they are *bound to* has a type

In [2]:
typeof(x)

Int64

We can re-assign ```x``` to another value of a different type

In [3]:
x = 3.4

3.4

In [4]:
typeof(x)

Float64

In addition to ```Int64``` (integers) and ```Float64``` (double-precision floating point), we also have others numeric types, like rational and complex numbers:

In [5]:
x = 3//4
typeof(x)

Rational{Int64}

In [6]:
x = 4.1 + 3.4im
typeof(x)

ComplexF64 (alias for Complex{Float64})

The common operations works on all numerical types:

In [7]:
3//4 + 7//9

55//36

In [8]:
(4.2 + 3.4im)*(7 - 2im)

36.2 + 15.4im

Exponentiation works with ```^```:

In [9]:
2^10

1024

If we need integer division we can use $\div$

In [10]:
13 ÷ 5

2

The reminder is, as in many other languages, ```%```:

In [11]:
13 % 5

3

### Characters and Strings

The ```Char``` type is a single UTF-8 character represented in the code by enclosing it in single quotes

In [12]:
'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [13]:
'🐱'

'🐱': Unicode U+1F431 (category So: Symbol, other)

A string is a (finite) sequence of characters and they are represented in the code by enclosing it in either double quotes or triple double quotes. Strings can span multiple lines

In [14]:
"Hello World"

"Hello World"

In [15]:
"""Hello
World"""

"Hello\nWorld"

In [16]:
"""Hello "Cruel" World"""

"Hello \"Cruel\" World"

Strings can be concatenated with ```*``` (and not ```+``` like in other languages)

In [17]:
"Hello" * " " * "World"

"Hello World"

Strings can be interpolated by using ```$```:

In [18]:
x = 4
"The value of x is $x"

"The value of x is 4"

In [19]:
"The result of x + 3 is $(x + 3)"

"The result of x + 3 is 7"

Other kinds of Strings literals exists (e.g., binary, regular expressions):

In [20]:
b"binary values" # An array of unsigned 8 bits integers

13-element Base.CodeUnits{UInt8, String}:
 0x62
 0x69
 0x6e
 0x61
 0x72
 0x79
 0x20
 0x76
 0x61
 0x6c
 0x75
 0x65
 0x73

In [21]:
r"[a-z]+\s*" # A regular expression

r"[a-z]+\s*"

### Symbols

A special kind of type is the ```Symbol``` type:

In [22]:
Symbol("hello")

:hello

In [23]:
typeof(:foo)

Symbol

Symbols are *interned strings*. You can use them, for example, as keywords (no need to use a String), but they have many other uses.

Symbols should be familiar to people programming in Lisp.

## Array, Dictionaries, and Tuples

### Arrays

Arrays can be defined similary to languages like Python by encosing the values in square brackets

In [4]:
v = [2,4,6,8]

4-element Vector{Int64}:
 2
 4
 6
 8

A one dimensional array of ```Int64```.

We can obtain the type of the elements contained in an array with ```eltype```

In [25]:
eltype(v)

Int64

and the length of the array by using ```length```

In [26]:
length(v)

4

Arrays can be of mixed types (might not be the best for efficiency)

In [27]:
v2 = [1, 3.4, "Hello"]

3-element Vector{Any}:
 1
 3.4
  "Hello"

In Julia, array are by default indexed from ```1``` and not from ```0```

In [28]:
v[1]

2

In [29]:
v[length(v)]

8

We can actually use any starting index with the package ```OffsetArrays.jl```

We can also retrieve the first and last element of the array using ```begin``` and ```end``` as indexes:

In [30]:
v[begin]

2

In [31]:
v[end]

8

#### Slices and viewes

As with many modern languages, arrays can be sliced using the syntax ```start_index:end_index```

In [5]:
v[2:3]

2-element Vector{Int64}:
 4
 6

Slices can be assigned to variables. In that case a *copy* is made

In [6]:
w = v[2:3]

2-element Vector{Int64}:
 4
 6

In [7]:
w[1] = 0
v

4-element Vector{Int64}:
 2
 4
 6
 8

If we want to refer to the same underlying memory we use ```view```

In [35]:
z = view(v,2:3)

2-element view(::Vector{Int64}, 2:3) with eltype Int64:
 4
 6

In [36]:
z[1] = 0
v

4-element Vector{Int64}:
 2
 0
 6
 8

#### Broadcasting

We may want to assign the same value to an entire slice of an array.

However, this will give an error:

In [37]:
v[1:3] = 4

ArgumentError: ArgumentError: indexed assignment with a single value to possibly many locations is not supported; perhaps use broadcasting `.=` instead?

We can prepend ```.``` to assignements (and any function call) to "broadcast" a value:

In [10]:
v[1:3] .= 4
v

4-element Vector{Int64}:
 4
 4
 4
 8

In [11]:
v

4-element Vector{Int64}:
 4
 4
 4
 8

#### Multidimensional arrays

Julia supports multi-dimensional array. 

We can write them remembering the following rules:

- Arguments separated by semicolons ```;``` or newlines are vertically concatenated
- Arguments separated by spaces or tabs are horizontally concatenated

In [40]:
M = [0 1 0 0
     1 0 0 1
     0 0 1 1]

3×4 Matrix{Int64}:
 0  1  0  0
 1  0  0  1
 0  0  1  1

We can obtain the dimensions of a multi-dimensional array using the ```ndims``` function

In [41]:
ndims(M)

2

And the length of a specific dimension using the ```size``` function

In [42]:
size(M)

(3, 4)

Indexing is made by using all indexes, separated by commas, inside square brackets:

In [43]:
M[1,2]

1

Notice that multidimensional arrays and arrays-of-arrays are different!

In [44]:
M2 = [[0,1,0,0], [1,0,0,1], [0,0,1,1]]

3-element Vector{Vector{Int64}}:
 [0, 1, 0, 0]
 [1, 0, 0, 1]
 [0, 0, 1, 1]

As before, we can slice the arrays. This time along multiple dimensions:

In [45]:
M[1:2,2:4]

2×3 Matrix{Int64}:
 1  0  0
 0  0  1

In [46]:
M[2:3,:]

2×4 Matrix{Int64}:
 1  0  0  1
 0  0  1  1

In [47]:
M[:,2:4]

3×3 Matrix{Int64}:
 1  0  0
 0  0  1
 0  1  1

As before, we can create views of the array

In [48]:
A = view(M, 2:3, 2:4)
A[1,1] = 99

99

In [49]:
M

3×4 Matrix{Int64}:
 0   1  0  0
 1  99  0  1
 0   0  1  1

And the shape of an array can be changed via the function ```reshape```:

In [50]:
reshape(M, 4, 3)

4×3 Matrix{Int64}:
 0  99  1
 1   0  0
 0   0  1
 1   0  1

In [51]:
reshape(M, 2, 3, 2)

2×3×2 Array{Int64, 3}:
[:, :, 1] =
 0  0  99
 1  1   0

[:, :, 2] =
 0  1  1
 0  0  1

In [52]:
zeros(2,4,3)

2×4×3 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

#### Array Comprehension

As with list comprehension in languages like Python, Julia also supports array comprehension

In [53]:
squares = [i^2 for i in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [54]:
mult_table = [i * j for i in 1:5, j in 1:10]

5×10 Matrix{Int64}:
 1   2   3   4   5   6   7   8   9  10
 2   4   6   8  10  12  14  16  18  20
 3   6   9  12  15  18  21  24  27  30
 4   8  12  16  20  24  28  32  36  40
 5  10  15  20  25  30  35  40  45  50

### Dictionaries

Dictionaries represent maps from a set $K$ of keys to a set $V$ of values

In [55]:
d = Dict('a' => 1, 2 => "text", :foo => :bar)

Dict{Any, Any} with 3 entries:
  2    => "text"
  'a'  => 1
  :foo => :bar

Dictionaries can be indexed similarly to arrays

In [56]:
d['a']

1

Assignment for non existing keys is possible and will add the key to the dictionary

In [57]:
d['z'] = 26
d

Dict{Any, Any} with 4 entries:
  2    => "text"
  'a'  => 1
  :foo => :bar
  'z'  => 26

The keys and values of a dictionary can be obtained by using the functions ```keys``` and ```values```, respectively:

In [58]:
keys(d)

KeySet for a Dict{Any, Any} with 4 entries. Keys:
  2
  'a'
  :foo
  'z'

In [59]:
values(d)

ValueIterator for a Dict{Any, Any} with 4 entries. Values:
  "text"
  1
  :bar
  26

### Tuples

Tuples are fixed-length containers that cannot be modified (i.e., they are immutable).

In [60]:
tuple = (1.2, 2, "hello")

(1.2, 2, "hello")

In [61]:
typeof(tuple)

Tuple{Float64, Int64, String}

Tuples are indexed starting from $1$, like arrays

In [62]:
tuple[1]

1.2

For tuples consisting of only one element remember the comma at the end:

In [63]:
small_tuple = (3,)

(3,)

When created, tuples can also be *named*

In [64]:
named_tuple = (a = 1.2, b = 2, c = "hello")

(a = 1.2, b = 2, c = "hello")

The elements of the tuple can now be accessed using the names (in addition to the indexes) of the fields

In [65]:
named_tuple.b

2

When assigning values *from* a tuple, Julia supports some destructuring

In [66]:
x, y, z = tuple
y

2

This is useful when a function returns multiple outputs as a tuple

## Functions

### Named functions

Functions can be defined via the ```function``` keyword and terminated by ```end```:

In [67]:
function add_one_v1(x)
    return x + 1
end

add_one_v1 (generic function with 1 method)

The ```return``` keyword is not essential, the last value in the function is the one returned

In [68]:
function add_one_v2(x)
    x + 1
end

add_one_v2 (generic function with 1 method)

Simple functions can be defined in a single line without using the ```function``` keyword

In [69]:
add_one_v3(x) = x + 1

add_one_v3 (generic function with 1 method)

Functions can also return multiple values as a tuple

In [70]:
function add_and_mul(x, y)
    x + y, x * y
end

add_and_mul (generic function with 1 method)

In [71]:
a, m = add_and_mul(3, 4)

(7, 12)

#### Keyword arguments

Keyword arguments can be added after a semicolon in the argument list with a default value (in this case they are not mandatory) or without (in this case they are mandatory)

In [72]:
function add_constant(x; constant = 0)
    x + constant
end

add_constant (generic function with 1 method)

In [73]:
add_constant(3)

3

In [74]:
add_constant(3, constant = 5)

8

Functions can have a variable number of arguments. You can use ```...``` following a variable name to collect the remaining arguments in an array.

In [75]:
function varargs(x...)
    sum(x)
end

varargs (generic function with 1 method)

In [76]:
varargs(1,2,3)

6

### Anonymous (lambda) functions

Sometimes it is useful to define a function without giving it a name. We can use anonymous (lambda) functions

In [77]:
(x,y) -> x^2 + y^2

#14 (generic function with 1 method)

Functions can be assigned to variables and called like "normal" functions

In [78]:
ff = (x,y) -> x^2 + y^2
ff(2, 3)

13

In [79]:
typeof(ff)

var"#16#17"

### Broadcasting functions

Function call is among the operations that can be braodcasted using ```.```:

In [80]:
ff([1,2,3], [4,5,6]) # This gives an error

MethodError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)
Closest candidates are:
  ^(!Matched::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:730
  ^(!Matched::Rational, ::Integer) at rational.jl:477
  ^(!Matched::Complex{<:AbstractFloat}, ::Integer) at complex.jl:860
  ...

In [81]:
ff.([1,2,3], [4,5,6])

3-element Vector{Int64}:
 17
 29
 45

Since also the normal arithmetical operations are functions, they too can be broadcasted:

In [82]:
[1,2,3,4] .+ 1

4-element Vector{Int64}:
 2
 3
 4
 5

## Selection and Iteration

### Selection: ```if```, ```if```..```else```

Selection is performed, as usual, with the ```if``` construct

In [83]:
x = 2
if x < 3
    println("x is less than 3")
end

x is less than 3


Multiple conditions can be checked by combining them in a C-like way

In [84]:
if x < 3 && x % 2 == 0
    println("x even and less than 3")
end

x even and less than 3


As usual, an ```if``` statement can include an ```else``` part

In [85]:
if x < 3
    println("x is less than 3")
else
    println("x is at least 3")
end

x is less than 3


Multiple ```if``` statements can be nested with ```elseif```

In [86]:
if x < 3
    println("x is less than 3")
elseif x == 3
    println("x is exactly 3")
else
    println("x is more than 3")
end

x is less than 3


### Iteration: ```for``` and ```while```

Iteration has the usual ```for``` and ```while``` constructs

In [87]:
x = 1
while x ≤ 3
    println(x)
    x += 1
end

1
2
3


The ```for``` construct operates similarly to the ```for``` in Python. This means that we usually have ```for variable in container```.

In [88]:
for v in 1:5
    println(v)
end

1
2
3
4
5


It is actually possible to use $\in$ instead of ```in```

In [89]:
for v ∈ [1,2,3]
    println(v)
end

1
2
3


### Functional constructs

Some common operations can better be expressed as functional constructs (e.g., ```map```, ```filter```) or array comprehension instead of using loops directly

```map``` applies a _unary_ function to all the elements of a container

In [90]:
map(x -> x^2 + x, [1,2,3,4,5])

5-element Vector{Int64}:
  2
  6
 12
 20
 30

```reduce``` applies a _binary_ function to all elements of a container "merging" them in a single value

In [91]:
v = [4,5,6,7,3]
reduce(+, v)

25

Some kinds of reductions are so common that they have special functions defined

In [92]:
minimum(v)

3

In [93]:
maximum(v)

7

In [94]:
sum(v)

25

In [95]:
prod(v)

2520

Another common operation is to filter a collection taking only the elements respecting a certain condition

In [14]:
filter(x -> x ≥ 5, v)

MethodError: MethodError: objects of type String are not callable

Many complex operations can be carried by combining filtering, mapping, and reducting.

For example, let us compute the sum of the square of all the positive values inside a vector

In [97]:
v = rand(10) .- 0.5

10-element Vector{Float64}:
  0.022465884356081878
 -0.039992935468734614
  0.25714455210620657
 -0.2637302632786792
 -0.3693028119211045
  0.18029374374629015
 -0.3556826423181787
  0.4601153250201542
  0.4858683420281479
  0.11313482784022877

In [98]:
v1 = filter(x -> x ≥ 0, v)
v2 = map(x -> x^2, v1)
v3 = sum(v2)

0.5597075180458769

This application of functions where the output of one goes as input to the next is so common that a special idiom using ```|>``` exists. Similar operators exist, for example, in R and Clojure.

In [15]:
filter(x -> x ≥ 0, v) |> x -> x.^2 |> sum

224

In general the form ```x |> f``` applies ```f``` to ```x```, so ```x |> f |> g |> h``` is ```h(g(f(x)))```

## Types

Until now we have not investigated how types can be useful for functions. We will start by defining how type annotations works

Some types: ```Float64```, ```Rational```, ```Int64```, ```Number```, ```Real```, etc. The types have a hierarchy: for example ```Number``` includes all numeric types, while ```Real``` all real numbers, and so on.

In [100]:
function f_only_reals(x::Real, y::Real)
    x + y
end

f_only_reals (generic function with 1 method)

Now a call like this works:

In [101]:
f_only_reals(3.5,4.0)

7.5

While using a string will give an error

In [102]:
f_only_reals("hello",  "world") # This gives an error

MethodError: MethodError: no method matching f_only_reals(::String, ::String)

We can also annotate variables to force them to only contains values of a specific type

In [103]:
function g(x, y)
    v::Array{Int64,1} = [x,y]
    sum(v)
end

g (generic function with 1 method)

In [104]:
g(1,4)

5

Notice that some types have a parameter enclosed in curly brackets, like ```Array{Int64,1}``` or ```Rational{Int64}```.

They are type parameters, they have some similarities to templates in C++ or generics in Java.

It is possible to define union of types. For example if a parameter can be either a ```Float64``` or ```Int32``` we can define:

In [105]:
Union{Float64, Int32}

Union{Float64, Int32}

A useful type to define missing values is the ```Missing``` type, whose only value is ```missing```.

For example to define a function that accepts a one-dimensional array of ```Float64``` values or missing values we can define it using a union.

In [106]:
function f_missing(v::Array{Union{Float64,Missing},1})
    filter(x -> !ismissing(x), v) |> sum
end

f_missing (generic function with 1 method)

In [107]:
f_missing([3.5, missing, 5, 8, missing, -3])

13.5

In [108]:
missing + 4

missing

### Structures

We can define new (product) types by defining structures:

In [109]:
struct MyPair
    first
    second
end

We have now defined a new type (```MyComplex```) that can be instantiated and used as a "normal" type:

In [110]:
c = MyPair(3, 5)

MyPair(3, 5)

In [111]:
typeof(c)

MyPair

We can access the different fields by using the dot notation:

In [112]:
c.first

3

Notice that we **cannot** modify a struct, since by default they are _immutable_:

In [113]:
c.second = 4 # this gives an error

ErrorException: setfield!: immutable struct of type MyPair cannot be changed

If we really need a _mutable_ structure we must define it so

In [114]:
mutable struct MyMutablePair
    first
    second
end

In [115]:
p = MyMutablePair(4, 7)

MyMutablePair(4, 7)

In [116]:
p.second = 8

8

In [117]:
p

MyMutablePair(4, 8)

We can define a "template" structure by using a type parameter

In [118]:
struct MySameTypePair{T}
    first::T
    second::T
end

In [119]:
MySameTypePair(3,4)

MySameTypePair{Int64}(3, 4)

In [120]:
MySameTypePair{String}("Hello", "World")

MySameTypePair{String}("Hello", "World")

In [121]:
MySameTypePair(2, "hello") # This gives an error

MethodError: MethodError: no method matching MySameTypePair(::Int64, ::String)
Closest candidates are:
  MySameTypePair(::T, !Matched::T) where T at ~/Downloads/julia/Lecture 1.ipynb:2

Fields of a structure can be typed independently.

In [122]:
struct MyPairV2
    first::String
    second::Float64
end

## Multiple Dispatch

Why are types useful? 

- They provide a way to give an error if the type in the annotation is not respected
- They can be used for dispatch! (see [The Unreasonable Effectiveness of Multiple Dispatch by Stefan Karpinski](https://www.youtube.com/watch?v=kc9HwsxE1OY))

Until now we have defined a function only once, we might want to define it multiple times depending on the types of the parameters 

In [123]:
function h(x::Float64, y::Float64)
    println("x and y are float")
end

function h(x::Float64, y::Int64)
    println("x is float and y is integer")
end

function h(x::Int64, y::Float64)
    println("x is integer and y is float")
end

function h(x::Int64, y::Int64)
    println("x and y are integer")
end

h (generic function with 4 methods)

In [124]:
h(3.4, 2)
h(3, 2.7)

x is float and y is integer
x is integer and y is float


We can see how many _methods_ every function has:

In [125]:
methods(h)

# 4 methods for generic function "h":
[1] h(x::Float64, y::Float64) in Main at /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:1
[2] h(x::Float64, y::Int64) in Main at /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:5
[3] h(x::Int64, y::Float64) in Main at /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:9
[4] h(x::Int64, y::Int64) in Main at /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:13

We can see it even for built-in functions

In [126]:
methods(+)

# 206 methods for generic function "+":
[1] +(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87
[2] +(x::T, y::T) where T<:Union{Float16, Float32, Float64} in Base at float.jl:383
[3] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:531
[4] +(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:537
[5] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:398
[6] +(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:406
[7] +(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:414
[8] +(x::Union{Dates.CompoundPeriod, Dates.Period}) in Dates at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Dates/src/periods.jl:378
[9] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.SymTridiagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/tridiag.jl:207
[10] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Symmetric) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:485
[11] +(A::LinearAlgebra.SymTridiagonal{var"#s883", V} where {var"#s883"<:Real, V<:AbstractVector{var"#s883"}}, B::LinearAlgebra.Hermitian) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:487
[12] +(x::LinearAlgebra.SymTridiagonal, H::LinearAlgebra.UpperHessenberg) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/hessenberg.jl:109
[13] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:157
[14] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Tridiagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:171
[15] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:225
[16] +(A::LinearAlgebra.SymTridiagonal{var"#s885", V} where {var"#s885"<:Number, V<:AbstractVector{var"#s885"}}, B::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:243
[17] +(x::Rational, y::Integer) in Base at rational.jl:313
[18] +(Da::LinearAlgebra.Diagonal, Db::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:184
[19] +(D::LinearAlgebra.Diagonal, S::LinearAlgebra.Symmetric) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:188
[20] +(D::LinearAlgebra.Diagonal{var"#s885", V} where {var"#s885"<:Real, V<:AbstractVector{var"#s885"}}, H::LinearAlgebra.Hermitian) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:194
[21] +(x::LinearAlgebra.Diagonal, H::LinearAlgebra.UpperHessenberg) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/hessenberg.jl:109
[22] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:137
[23] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.SymTridiagonal) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:147
[24] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Tridiagonal) in LinearAlgebra at /Applications/Julia-1.8.

Why is multiple dispatch useful?

We can write a function using, for example, ```+``` and the correct implementation will be the one used.

For example we can write a function working with matrix multiplication and the correct implementation (depending if the matrix is, for example, diagonal, tridiagonal, etc) will be used.

## Environments and Packages

It is essential to be able to create multiple environments, each one with a different set of packages installed and to make the environment reproducible across multiple machines.

We can either work directly with the ```Pkg``` package (you can import it with ```using Pkg```) or on the REPL by going into the package management with ```]```

 - ```activate``` allows to create a (or activate an existing) new self-contained project. All installs will be local to the project. The ```Manifest.toml``` and ```Project.toml``` files contains the information about the installed packages and their versions
 - ```add package_name``` install the package, resolving the dependencies. For example, ```add IJulia``` to have a notebook interface.
 - ```rm package_name``` to remove a package from the current project
 - ```update``` to update the packages

All code that we will see in the course can be installed as packages or it is in the base library.

## Macros

Macros are a tool for _metaprogramming_. That is, for writing code that writes code. They are well known in the Lisp word and are gaining popularity in other languages.

Recall that the arguments of a function are evaluated before being passed to a function.

Arguments to a macro are not evaluated. The macro receives the (representation of the) code and can manipulate it returning new code.

Macro should not be used too estensively, but they are a powerful tool. In Julia they always have ```@``` before their name

#### Some useful macros

The ```@time``` macro allows to find the amount of time spent in executing a piece of code

In [128]:
@time map(x->x^2, rand(1000));

  0.014161 seconds (54.80 k allocations: 2.863 MiB, 80.92% compilation time)


It is possible to explore which method of a function Julia is going to call using the ```@which``` macro

In [129]:
@which 3 + 5

+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87

It is actually possible to observe which is the code generate by Julia with a collection of macros ```@code_lowered```, ```@code_typed```, ```@code_llvm```, ```@code_native```

In [130]:
@code_lowered 3 + 5

CodeInfo(
1 ─ %1 = Base.add_int(x, y)
└──      return %1
)

In [131]:
@code_typed 3 + 5

CodeInfo(
1 ─ %1 = Base.add_int(x, y)::Int64
└──      return %1
) => Int64

In [132]:
@code_llvm 3 + 5

;  @ int.jl:87 within `+`
define i64 @"julia_+_5102"(i64 signext %0, i64 signext %1) #0 {
top:
  %2 = add i64 %1, %0
  ret i64 %2
}


In [133]:
@code_native 3 + 5

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 13, 0
	.globl	"_julia_+_5137"                 ; -- Begin function julia_+_5137
	.p2align	2
"_julia_+_5137":                        ; @"julia_+_5137"
; ┌ @ int.jl:87 within `+`
	.cfi_startproc
; %bb.0:                                ; %top
	add	x0, x1, x0
	ret
	.cfi_endproc
; └
                                        ; -- End function
.subsections_via_symbols


We can see how a macro acts on the code via ```@macroexpand```

In [134]:
@macroexpand @timed 3 + 5

quote
    #= timing.jl:460 =#
    $(Expr(:meta, :force_compile))
    #= timing.jl:461 =#
    local var"#76#stats" = Base.gc_num()
    #= timing.jl:462 =#
    local var"#78#elapsedtime" = Base.time_ns()
    #= timing.jl:463 =#
    local var"#77#val" = 3 + 5
    #= timing.jl:464 =#
    var"#78#elapsedtime" = Base.time_ns() - var"#78#elapsedtime"
    #= timing.jl:465 =#
    local var"#79#diff" = Base.GC_Diff(Base.gc_num(), var"#76#stats")
    #= timing.jl:466 =#
    (value = var"#77#val", time = var"#78#elapsedtime" / 1.0e9, bytes = (var"#79#diff").allocd, gctime = (var"#79#diff").total_time / 1.0e9, gcstats = var"#79#diff")
end

Macros are one of the features that allows Julia to be flexible.

#### Code representation

Can can be forced not be evaluated by putting it in a ```quote``` block or by using the ```:``` operator

In [135]:
code1 = quote
    x = 4
    y = 6
    x + y
end

code2 = :(3 + 5)
code1

quote
    #= /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:2 =#
    x = 4
    #= /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:3 =#
    y = 6
    #= /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:4 =#
    x + y
end

We can manipulate code as data (a concept that should be familiar to programmers in the lisp family of languages)

In [136]:
typeof(code2)

Expr

In [137]:
Meta.show_sexpr(code2)

(:call, :+, 3, 5)

In [138]:
code2.head

:call

In [139]:
code2.args

3-element Vector{Any}:
  :+
 3
 5

The code starts with a function call (```:call```) where the function is ```+``` and the arguments are ```3``` and ```5```.

We can modify the code directly

In [140]:
code2.args[1] = :* # We modify the function from + to *

:*

In [141]:
code2

:(3 * 5)

In [142]:
eval(code2)

15

## Linear Algebra

Let see some common linear algebra operations.

We generate some random matrices and vectors

In [143]:
A = rand(3, 3) # Random 3 by 3 matrix

3×3 Matrix{Float64}:
 0.0722176  0.571736  0.954887
 0.061473   0.77935   0.361688
 0.77375    0.793031  0.614209

In [144]:
b = rand(3) # random vector of three elements

3-element Vector{Float64}:
 0.49795364148539645
 0.42721971610342213
 0.7748709647165973

The ```\``` operator solves the linear system $Ax = b$.

In [145]:
x = A\b

3-element Vector{Float64}:
 0.3909668126347051
 0.4002694421668466
 0.25225021505805856

Matrix multiplication, addition, etc. are already possible via multiple dispatch using the same operators used for numbers

In [146]:
A*b

3-element Vector{Float64}:
 1.0201320534509684
 0.6438260571063599
 1.2000228870906502

In [147]:
A^3

3×3 Matrix{Float64}:
 0.799919  2.0989   1.72364
 0.516537  1.3605   0.998994
 1.22252   2.65015  1.97512

In [148]:
b * transpose(b)

3×3 Matrix{Float64}:
 0.247958  0.212736  0.38585
 0.212736  0.182517  0.33104
 0.38585   0.33104   0.600425

Notice that all operation like ```reduce```, ```prod```, ```sum``` works on arrays of matrices as well. 

In [149]:
sum([rand(2,2) for i in 1:5])

2×2 Matrix{Float64}:
 2.36155  2.36845
 1.80286  2.68329

In [150]:
prod([rand(2,2) for i in 1:5])

2×2 Matrix{Float64}:
 0.201362  0.083326
 0.137285  0.0568159

We can use more linear algebra functions by importing the module ```LinearAlgebra```

In [151]:
using LinearAlgebra

We have now access to code for findig eigenvalues and eigenvectors

In [152]:
A = [1 0 2
     3 4 8
     0 0 7]

eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 1.0
 4.0
 7.0
vectors:
3×3 Matrix{Float64}:
  0.707107  0.0  0.104828
 -0.707107  1.0  0.943456
  0.0       0.0  0.314485

Or to compute, for example, the SVD

In [153]:
svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.181535  -0.053882   0.981907
 -0.80341    0.583919  -0.116492
 -0.567077  -0.810022  -0.149291
singular values:
3-element Vector{Float64}:
 11.524759614107468
  3.0923530280991645
  0.7856644236843773
Vt factor:
3×3 Matrix{Float64}:
 -0.224887  -0.278847  -0.933633
  0.549056   0.755307  -0.357839
  0.804962  -0.59309   -0.0167561

But how many methods do we have to compute the SVD?

In [154]:
methods(svd)

# 14 methods for generic function "svd":
[1] svd(A::StridedVecOrMat{T}; full, alg) where T<:Union{Float16, ComplexF16} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:181
[2] svd(A::StridedMatrix{T}, B::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:407
[3] svd(A::StridedVecOrMat{T}; full, alg) where T in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:178
[4] svd(A::StridedMatrix{TA}, B::StridedMatrix{TB}) where {TA, TB} in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:460
[5] svd(A::Union{Hermitian{T, S}, Hermitian{Complex{T}, S}, Symmetric{T, S}} where {T<:Real, S}; full) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:649
[6] svd(D::Diagonal{T, V} where V<:AbstractVector{T}) where T<:Number in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:735
[7] svd(A::Transpose; full, alg) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:195
[8] svd(M::Bidiagonal; kw...) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/bidiag.jl:219
[9] svd(x::Integer; full, alg) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:188
[10] svd(x::Number; full, alg) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:185
[11] svd(x::Number, y::Number) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:467
[12] svd(A::Adjoint; full, alg) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/svd.jl:191
[13] svd(A::LinearAlgebra.AbstractTriangular; kwargs...) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/triangular.jl:2655
[14] svd(A::BitMatrix) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/bitarray.jl:90

Let us create a _diagonal_ matrix:

In [155]:
D = Diagonal([1.,5.,9.])

3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   5.0   ⋅ 
  ⋅    ⋅   9.0

We can still call the ```svd``` function and the correct implementation will be called 

In [156]:
svd(D)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  1.0  0.0
 1.0  0.0  0.0
singular values:
3-element Vector{Float64}:
 9.0
 5.0
 1.0
Vt factor:
3×3 Matrix{Float64}:
 0.0  0.0  1.0
 0.0  1.0  0.0
 1.0  0.0  0.0

In [157]:
@which svd(D)

svd(D::Diagonal{T, V} where V<:AbstractVector{T}) where T<:Number in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:735

We have many different kinds of matrices

In [158]:
T = LowerTriangular(A)

3×3 LowerTriangular{Int64, Matrix{Int64}}:
 1  ⋅  ⋅
 3  4  ⋅
 0  0  7

In [159]:
svd(T)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 0.0  -0.122183  -0.992508
 0.0  -0.992508   0.122183
 1.0   0.0        0.0
singular values:
3-element Vector{Float64}:
 7.0
 5.036796290982293
 0.794155603863008
Vt factor:
3×3 Matrix{Float64}:
  0.0        0.0        1.0
 -0.615412  -0.788205  -0.0
 -0.788205   0.615412   0.0

In [160]:
@which svd(T)

svd(A::LinearAlgebra.AbstractTriangular; kwargs...) in LinearAlgebra at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/triangular.jl:2655

This allows to write the same code and have it compile down to the correct (and optimized) implementation

### The end

The following is valid Julia code:

In [161]:
for 🌙 in '🌑':'🌘'
    print(🌙)
end

🌑🌒🌓🌔🌕🌖🌗🌘

## Extras

#### Custom ```+``` for string concatenation

Let us add ```+``` as string concatenation. We start by importing ```Base:+```

In [162]:
import Base:+

We define how ```+``` should work with strings

In [163]:
function +(x::String, y::String)
    x * y
end

+ (generic function with 207 methods)

In [164]:
"Hello " + "World"

"Hello World"

And now functions written **before** we wrote our ```+``` implementation will make use of it.

In [165]:
sum(["Hello", " ", "world"])

"Hello world"

#### A ```@unless``` macro

We want to write a macro that execute a piece of code _unless_ a certain condition is satisfied

In [166]:
macro unless(test, body)
    quote
        if !$test
            $body
        end
    end
end

@unless (macro with 1 method)

In [167]:
x = 4
@unless x ∈ 1:5 println("Foo")
@unless x > 10 println("Bar")

Bar


In [168]:
@macroexpand @unless x ∈ 1:5 println("Foo")

quote
    #= /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:3 =#
    if !(Main.x ∈ 1:5)
        #= /Users/lucamanzoni/Downloads/julia/Lecture 1.ipynb:4 =#
        Main.println("Foo")
    end
end

#### Push!, Sort!, and functions modifying their arguments

Some functions modify their arguments. By convention such functions are denoted by a ```!``` at the end of the name.

For example ```push!``` and ```pop!``` can be used to add and remove elements at the end of an array

In [169]:
v = [1,2,3,4]
push!(v, 5)
v

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [170]:
pop!(v)
v

4-element Vector{Int64}:
 1
 2
 3
 4

Some functions have two versions. Like ```sort```, returning a sorted copy of the original array, and ```sort!```, sorting the array passed as argument directly.

In [171]:
w = rand(10)

10-element Vector{Float64}:
 0.5004295649416891
 0.34710075910075566
 0.4684865759199486
 0.9728697655785353
 0.8811981971745537
 0.3956292695045227
 0.9390323725809224
 0.960710832808453
 0.48402403659274973
 0.875653114503923

In [172]:
sort(w)

10-element Vector{Float64}:
 0.34710075910075566
 0.3956292695045227
 0.4684865759199486
 0.48402403659274973
 0.5004295649416891
 0.875653114503923
 0.8811981971745537
 0.9390323725809224
 0.960710832808453
 0.9728697655785353

In [173]:
w

10-element Vector{Float64}:
 0.5004295649416891
 0.34710075910075566
 0.4684865759199486
 0.9728697655785353
 0.8811981971745537
 0.3956292695045227
 0.9390323725809224
 0.960710832808453
 0.48402403659274973
 0.875653114503923

In [174]:
sort!(w)

10-element Vector{Float64}:
 0.34710075910075566
 0.3956292695045227
 0.4684865759199486
 0.48402403659274973
 0.5004295649416891
 0.875653114503923
 0.8811981971745537
 0.9390323725809224
 0.960710832808453
 0.9728697655785353

In [175]:
w

10-element Vector{Float64}:
 0.34710075910075566
 0.3956292695045227
 0.4684865759199486
 0.48402403659274973
 0.5004295649416891
 0.875653114503923
 0.8811981971745537
 0.9390323725809224
 0.960710832808453
 0.9728697655785353