In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.concatenate([arr1,arr2]))

[1 2 3 4 5 6 7 8]


In [3]:
A = arr1.reshape(2,2)
B = arr2.reshape(2,2)
print(np.concatenate([A,B]))
print(np.concatenate([A,B],axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [4]:
vect1 = np.array([1,2,3])
vect2 = np.array([[4,5,6],[7,8,9]])
print(vect1,np.shape(vect1))
print(vect2,np.shape(vect2))
print(np.vstack([vect1,vect2]))
print(np.hstack([vect1.reshape(3,1),vect2.T]))

[1 2 3] (3,)
[[4 5 6]
 [7 8 9]] (2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
A = np.arange(0, 16).reshape(4, 4)
print(A, '\n')

print(A[1:3, 1:3],'\n')
print(A[:3, 2:],'\n')
print(A[:, 0:3:2],'\n')
print(A[::2, :], '\n')
print(A[::-1, :],'\n')
print(A[0:-2, :], '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 5  6]
 [ 9 10]] 

[[ 2  3]
 [ 6  7]
 [10 11]] 

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]] 

[[ 0  1  2  3]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]] 

[[0 1 2 3]
 [4 5 6 7]] 



In [5]:
v = np.array(['ciao', 'ccc'])

print(type(v))

<class 'numpy.ndarray'>
[2 4 6]


In [2]:
A = arr1.reshape(2,2)
B = arr2.reshape(2,2)

print(np.vstack([A, B]))
print(np.hstack([A, B]))

NameError: name 'arr1' is not defined

numpy non cambia l'array data type (forza l'input nel tipo dell'array)

In [8]:
A[1, 1] = 7.92

print(A)
print(A.dtype, '\n')

C = A.astype('float')
print(C)
print(C.dtype)

[[1 2]
 [3 7]]
int64 

[[1. 2.]
 [3. 7.]]
float64


In [12]:
C[1, 1] = 111

print(A)
print(C, '\n')

# '=' crea una reference
D = C
D[0, 0] = 4

print(C, '\n')

# per fare una copia devo usare copy()
E = C.copy()
E[0, 0] = 6

print(C, '\n')

[[1 2]
 [3 7]]
[[  4.   2.]
 [  3. 111.]] 

[[  4.   2.]
 [  3. 111.]] 

[[  4.   2.]
 [  3. 111.]] 



argmin e argmax restituiscono gli indici e non i valori

In [16]:
Z = np.linspace(0, 10, 9).reshape(3, 3)
Z = np.hstack([Z, np.array([[1, 2, 3]]).T])

print(Z)

print(np.argmax(Z))
print(np.argmin(Z))

[[ 0.    1.25  2.5   1.  ]
 [ 3.75  5.    6.25  2.  ]
 [ 7.5   8.75 10.    3.  ]]
10
0


%%timeit è una cell magic function di jupyter: deve sempre essere messa all'inizio di una cella

In [18]:
A=np.array(range(0,900)).reshape(30,30)
B=np.array(range(34,934)).reshape(30,30)

In [19]:
%%timeit
np.matmul(A,B)

30.7 µs ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [20]:
A=[[x for x in range(30)] for i in range(30)]
B=[[x+34 for x in range(30)] for i in range(30)]

In [21]:
%%timeit
np.matmul(A,B)

186 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [12]:
np.array([[1, 2, 3], [2, 3, 4]])

array([[1, 2, 3],
       [2, 3, 4]])